[package]
name = "stegfile"
version = "0.1.0"
edition = "2021"
description = "Hides one file among several images."

[dependencies]
tempfile = "3.3"
clap = { version = "4.5.15", features = ["derive"] }
